### ISSUE TITLE
自动建立机制有问题

### ISSUE THREAD

**Issue by WolkeAtreide** [frostime/siyuan-plugin-open-diary#9]
![image](https://user-images.githubusercontent.com/101959415/235055162-c680725d-5731-43bd-aaa9-26f7ac51c0e6.png)
wouizd
我的操作习惯是在数据库中建立日记。而挂件的默认规则是列表第一个（也就是书）和已选中库同时建立，所以每次开软件我都要先把书里面的dailynote删掉再记笔记，有点麻烦。
能更改一下排序规则么？或者不要自动触发第一个
![image](https://user-images.githubusercontent.com/101959415/235055552-42cf900a-31f4-471c-8f54-cd25687a74ef.png)

**Comment by frostime** [comment]
1. 排序规则和笔记本在文档数中的排序保持一致，如果希望调整排序，可以在文档数中拖动「数据库」到第一项，然后按快捷键「Ctrl + Alt +U」
2. 如果不希望自动创建笔记，可以试着在设置里面关掉「自动打开」功能
   ![image](https://user-images.githubusercontent.com/27268127/235055951-0e389d87-5e87-4a31-94d5-f9631a5f22df.png)

**Comment by frostime** [comment]
![image](https://user-images.githubusercontent.com/27268127/235056609-d9d2fc1d-ca7f-4f2b-9cfc-bb96b9601912.png)
![image](https://user-images.githubusercontent.com/27268127/235056663-b7e3819b-d371-4283-a542-295f96c78920.png)

Ctrl + Alt + U 更新状态

![image](https://user-images.githubusercontent.com/27268127/235056714-df1b994c-2779-4b77-a07c-e7da1717dbbb.png)

**Comment by WolkeAtreide** [comment]
霍，我以为能够把第一个这个特性必选去掉。文档树排序我比较喜欢按自然数排序，否则就变成这样了。不过如果不好改也没关系。一样用
![image](https://user-images.githubusercontent.com/101959415/235069961-ae3f673c-a5d5-4168-9e8d-1d7c7b51677e.png)

**Comment by frostime** [comment]
@WolkeAtreide 

哦，我理解你的意思了，因为我之前文档数排序一直是按照自定义排序来，没有考虑过别的排序方案。而插件下拉框里面的的文档排序是按照自定义排序下的规则来的。

![image](https://user-images.githubusercontent.com/27268127/235072117-9a6ac396-a62d-4538-a5c9-32302355ed5f.png)


你可以试一下：

1. 把排序规则调成「自定义排序」，把你希望的默认笔记本放到第一个位置
2. 更新状态
3. 换回原来你用的排序规则

这样的话文档数里面的笔记本显示顺序不变，然而下拉框里面的第一个笔记本就是你希望的默认笔记本。

------

我后面看情况优化一下，后面会给一个选项让用户决定下拉框是根据自定义排序来还是显示排序来。

至于让用户自定义选择默认笔记本，这个就要等到更后面了。
